---
title: "policy_and_outcomes"
author: "Drew Walker"
date: "6/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(randomForest)
library(tm)
```

```{r alcpolicy}

alc_policies <- read_csv("Comparing state COVID Alc Policy Sources.csv")
```

```{r, outcomes_data}
outcomes_data <- read_csv("merged_clean_bwm_wave2_edited2.csv")

#Merge with fips to groupby?

str(outcomes_data$State)

outcomes_data$State <- as.factor(outcomes_data$State)
outcomes_data$beer <- as.factor(outcomes_data$beer)
outcomes_data$wine <- as.factor(outcomes_data$wine)
outcomes_data$mixed_drinks <- as.factor(outcomes_data$mixed_drinks)



#barpolicydata_state <- outcomes_data %>% 
#  group_by(State) %>% 
#  summarise(barcount = n(),
#            beercount = sum(beer == "1", na.rm = TRUE),
#            no_beercount = sum(beer == "0", na.rm = #TRUE),
#            na_beercount = sum(is.na(beer)),
#            winecount = sum(wine == "1", na.rm = TRUE),
#            no_winecount = sum(wine == "0", na.rm = #TRUE),
#            na_winecount = sum(is.na(wine)),
#            mixed_drinkscount = sum(mixed_drinks == "1", #na.rm = TRUE),
#            no_mixed_drinkscount = sum(mixed_drinks == #"0", na.rm = TRUE),
#            na_mixed_drinkscount = #sum(is.na(mixed_drinks)))
#
##Join with state APIS/ABCA/Doug scores
#
#barpolicydata_state_merge <- barpolicydata_state %>% 
#  rename(State_abbr = State)

outcomes_data_clean <- outcomes_data %>% 
  rename(State_abbr = State)

joined_policy_and_outcomes <- left_join(outcomes_data_clean,alc_policies, by = "State_abbr")
```

```{r, cleaning-nabca}

#Clean NABCA data
clean_joined_policy_and_outcomes <- joined_policy_and_outcomes %>% 
 mutate(
   NABCA_spirits_bars = case_when(
      grepl("Yes|Already Permitted|Varies by Localit", Spirits_togo_NABCA_bars, ignore.case = TRUE) ~ 1,
      grepl("No|For Food Only", Spirits_togo_NABCA_bars, ignore.case = TRUE)~0),
    NABCA_spirits_rest = case_when(
      grepl("Yes|Already Permitted|Varies by Localit", Spirits_togo_NABCA_rest, ignore.case = TRUE) ~ 1,
      grepl("No|For Food Only", Spirits_togo_NABCA_rest, ignore.case = TRUE)~0))
```



```{r, outcomes_data}
write_csv(clean_joined_policy_and_outcomes,  "joined_togo_policy_and_bar_outcomes_data.csv", na = "") 


#Filtered for places that do not sell food 

wave1_food_data <- read_csv("Wave1_cleaned.csv")

cleaned_joined_policy_outcomes_merge_wave1 <- left_join(clean_joined_policy_and_outcomes,wave1_food_data, by = "UID")

cleaned_joined_policy_outcomes_no_food_or_more_midnights <- cleaned_joined_policy_outcomes_merge_wave1 %>% 
  filter(Food == 0 | OpenMidnitePerWeek > 3)

write_csv(cleaned_joined_policy_outcomes_no_food_or_more_midnights, "no_food_or_more_midnights_data.csv", na = "")

and_cleaned_joined_policy_outcomes_no_food_and_more_midnights <- cleaned_joined_policy_outcomes_merge_wave1 %>% 
  filter(OpenMidnitePerWeek > 3)

write_csv(and_cleaned_joined_policy_outcomes_no_food_and_more_midnights, "bars more than 3 midnights.csv", na = "")

restaurants <- cleaned_joined_policy_outcomes_merge_wave1 %>% 
  filter(OpenMidnitePerWeek < 4)

write_csv(restaurants, "restaurants.csv", na = "")

```

```{r, pricechanges}
pricechanges <- cleaned_joined_policy_outcomes_merge_wave1 %>% 
  mutate(beer_price_change = Beer_Price.x - Beer_Price.y,
         vodka_price_change = Vodka_price.x - Vodka_price.y)
write_csv(pricechanges, "pricechanges.csv", na = "")
```


# Wave 2 Excluded outlets from analytic sample
```{r, excluded-wave2 }
na_clean_joined_policy_outcomes <- clean_joined_policy_and_outcomes %>% 
  filter(is.na(alcohol_togo))
# is.na() for beer/wine/mixed_drinks, this is 182. 
# for alcohol_togo = 179
# Policies are about same 

```

